import type { SportIcon as SportIconName } from '@juandavidfuentes/indomitox-shared';
import {
  AirplaneTilt,
  ArrowFatLinesDown,
  ArrowLineDown,
  Balloon,
  Bicycle,
  Binoculars,
  Bird,
  Boat,
  Cactus,
  Campfire,
  Compass,
  Drop,
  Fish,
  Flame,
  Goggles,
  Horse,
  Island,
  Jeep,
  Lifebuoy,
  Lightning,
  Motorcycle,
  Mountains,
  Parachute,
  Path,
  PersonSimpleBike,
  PersonSimpleHike,
  PersonSimpleRun,
  PersonSimpleSki,
  PersonSimpleSwim,
  PersonSimpleWalk,
  Pulse,
  RocketLaunch,
  Sailboat,
  Snowflake,
  Sun,
  Target,
  Tent,
  TreeEvergreen,
  Waves,
  Wind,
  type Icon,
  type IconProps,
} from '@phosphor-icons/react';

/** Íconos de Phosphor permitidos para los deportes (SPORT_ICONS de shared). */
export const SPORT_ICON_COMPONENTS: Record<SportIconName, Icon> = {
  Waves,
  Boat,
  Sailboat,
  Lifebuoy,
  Drop,
  Goggles,
  Fish,
  Wind,
  Parachute,
  AirplaneTilt,
  Bird,
  Balloon,
  ArrowFatLinesDown,
  ArrowLineDown,
  Path,
  Mountains,
  Bicycle,
  PersonSimpleBike,
  Motorcycle,
  Jeep,
  Horse,
  PersonSimpleHike,
  PersonSimpleWalk,
  PersonSimpleSwim,
  PersonSimpleRun,
  PersonSimpleSki,
  Sun,
  Cactus,
  Compass,
  Binoculars,
  Tent,
  Campfire,
  Flame,
  Lightning,
  RocketLaunch,
  Target,
  Pulse,
  TreeEvergreen,
  Island,
  Snowflake,
};

/** Ícono de un deporte (o la montaña si no tiene). Decorativo: el nombre va al lado. */
export function SportIcon({ icon, ...props }: { icon: SportIconName | null | undefined } & Omit<IconProps, 'name'>) {
  const Component = (icon && SPORT_ICON_COMPONENTS[icon]) || Mountains;
  return <Component aria-hidden="true" {...props} />;
}
